[package]
name = "tictactoe"
version = "0.1.0"
edition = "2018"

[dependencies]
jni = "0.19.0"
log = "0.4.14"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.10.1"

[lib]
crate_type = ["cdylib"]